'use client'

import { useState } from 'react'
import { ArrowUpRight, BookOpen, BriefcaseBusiness, Check, ChevronDown, Download, ExternalLink, FlaskConical, GraduationCap, Mail, MapPin, Menu, Moon, Phone, Quote, Sun, Users, X } from 'lucide-react'

const nav = ['About', 'Education', 'Publications', 'Projects', 'Skills', 'Leadership', 'Achievements', 'Contact']
const projects = [
  { title: 'Gadget Shop Management System', period: 'Fall 2023–2024', tools: ['Java', 'Swing', 'Oracle SQL', 'JDBC'], description: 'Engineered a retail inventory application using Java Swing and Oracle SQL, implementing JDBC-driven CRUD operations to streamline real-time gadget tracking and automated sales transactions.' },
  { title: 'Inventory Management System', period: 'Fall 2024–2025', tools: ['C#', '.NET Framework', 'Visual Studio', 'SQL Server'], description: 'Developed a scalable inventory management application using C# and the .NET framework to manage product records, stock levels, supplier information, and sales data with SQL Server integration for efficient data handling and report generation.' },
  { title: 'Tomato Leaf Disease Detection Using Deep Learning', period: '2025–2026', tools: ['Python', 'TensorFlow', 'Keras', 'CNN', 'Deep Learning'], description: 'Developed a deep learning-based image classification model to detect tomato leaf diseases using convolutional neural networks (CNN). Achieved accurate disease prediction to support early detection and improved agricultural decision making.', featured: true },
]
const skills = { Programming: ['Python', 'C++', 'Java', 'PHP', 'HTML', 'JavaScript', 'CSS'], Tools: ['TensorFlow', 'Keras', 'Scikit-learn'], 'Data Analysis': ['Pandas', 'Excel'], Research: ['Academic Writing', 'Data Collection'], 'Soft Skills': ['Communication', 'Teamwork', 'Problem Solving'] }
const achievements = ["Dean’s List Honors, AIUB — 2024–2025", "Dean’s List Honors, AIUB — 2023–2024", "Dean’s List Honors, AIUB — 2022–2023", 'IEEE Conference Paper Presentation (QPAIN 2026)']

function SectionHeading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) { return <div className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{intro && <p className="section-intro">{intro}</p>}</div> }
function Pill({ children }: { children: React.ReactNode }) { return <span className="pill">{children}</span> }

export default function Page() {
  const [menu, setMenu] = useState(false)
  const [dark, setDark] = useState(true)
  return <div className={dark ? 'site dark' : 'site'}>
    <header className="navbar"><a href="#home" className="brand"><span className="brand-mark">YR</span><span>Yousha Rashid</span></a><nav className={menu ? 'nav-links open' : 'nav-links'}>{nav.map(item => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenu(false)}>{item}</a>)}</nav><div className="nav-actions"><button className="icon-button" aria-label="Toggle color theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button><button className="menu-button icon-button" aria-label={menu ? 'Close menu' : 'Open menu'} onClick={() => setMenu(!menu)}>{menu ? <X size={19} /> : <Menu size={19} />}</button></div></header>
    <main>
      <section id="home" className="hero wrap"><div className="hero-copy"><p className="eyebrow reveal">COMPUTER SCIENCE & ENGINEERING</p><h1 className="reveal delay-1">Building with<br /><em>curiosity</em> & purpose.</h1><p className="hero-sub reveal delay-2">Dedicated and detail-oriented Computer Science and Engineering student with strong academic performance and a passion for learning, problem-solving, and developing innovative solutions.</p><div className="hero-buttons reveal delay-3"><a className="button primary" href="#projects">View My Work <ArrowUpRight size={16} /></a><a className="button secondary" href="/Yousha_Rashid_CV.pdf" download>Download CV <Download size={15} /></a></div><div className="hero-meta reveal delay-3"><Pill>AIUB</Pill><Pill>CGPA 3.85/4.00</Pill><Pill>AI/ML Researcher</Pill><Pill>Expected Graduation: August 2026</Pill></div></div><div className="portrait-wrap reveal delay-2"><div className="portrait-glow" /><div className="portrait"><img src="/yousha_profile_pic.png" alt="Yousha Rashid profile placeholder" /><div className="portrait-label"><span>Yousha Rashid</span><small>Dhaka, Bangladesh</small></div></div><div className="float-tag tag-one">Python</div><div className="float-tag tag-two">TensorFlow</div><div className="float-tag tag-three">AI / ML</div></div></section>
      <section id="about" className="wrap section about"><SectionHeading eyebrow="01 / ABOUT" title="A student of systems, research, and possibility." intro="I am an undergraduate Computer Science and Engineering student at American International University-Bangladesh, driven by the intersection of thoughtful engineering and applied research." /><div className="stats"><div><strong>3.85<span>/4.00</span></strong><small>Current CGPA</small></div><div><strong>5.00<span>/5.00</span></strong><small>HSC GPA</small></div><div><strong>5.00<span>/5.00</span></strong><small>SSC GPA</small></div><div><strong>2026</strong><small>Expected graduation</small></div></div></section>
      <section id="education" className="wrap section"><SectionHeading eyebrow="02 / EDUCATION" title="Academic foundation." /><div className="timeline"><article><div className="timeline-dot" /><div className="timeline-top"><span>2022–Present</span><GraduationCap size={18} /></div><h3>American International University-Bangladesh (AIUB)</h3><p>B.Sc. in Computer Science and Engineering (CSE)</p><b>CGPA: 3.85/4.00 (Current)</b><small>Expected Graduation: August 2026</small></article><article><div className="timeline-dot" /><div className="timeline-top"><span>2019–2020</span><GraduationCap size={18} /></div><h3>Dhaka City College</h3><p>Higher Secondary Certificate (HSC)</p><b>Group: Science · GPA: 5.00/5.00</b></article><article><div className="timeline-dot" /><div className="timeline-top"><span>2017–2018</span><GraduationCap size={18} /></div><h3>Shibchar Nanda Kumar Model Institution</h3><p>Secondary School Certificate (SSC)</p><b>Group: Science · GPA: 5.00/5.00</b></article></div></section>
      <section id="publications" className="wrap section"><SectionHeading eyebrow="03 / RESEARCH" title="Research & Publications" intro="Exploring the questions where intelligent systems meet meaningful, real-world outcomes." /><div className="publication-grid"><article className="publication-card primary-card"><div className="card-top"><Pill>IEEE Conference Presentation — 2026</Pill><FlaskConical size={22} /></div><h3>Tomato Leaf Disease Detection Using Deep Learning-Based Image Classification</h3><p>Md. Zahidul Haque, Firoz Ahmed, <strong>Yousha Rashid</strong></p><div className="pub-footer"><BookOpen size={16} /> 2026 IEEE 2nd International Conference on Quantum Photonics, Artificial Intelligence and Networking (QPAIN 2026), CUET, Bangladesh</div></article><article className="publication-card"><div className="card-top"><Pill>International Conference</Pill><FlaskConical size={22} /></div><h3>Industry 5.0–Driven Deep Learning Framework for Long-Term Global CO2 Emission Forecasting</h3><p>Md. Owafeeuzzaman Patwary, Apurbo Biswas, <strong>Yousha Rashid</strong>, Md. Rakibul Islam, Kazi Tanvir, Reazul Islam, Dipta Gomes</p><div className="pub-footer"><BookOpen size={16} /> International Conference on Electrical, Computer and Communication Technologies</div></article></div></section>
      <section id="projects" className="wrap section"><SectionHeading eyebrow="04 / SELECTED WORK" title="Featured Projects" /><div className="project-grid">{projects.map((project, i) => <article className={project.featured ? 'project-card featured' : 'project-card'} key={project.title}><div className="project-number">0{i + 1}</div><div className="project-info"><div className="card-top"><span className="period">{project.period}</span><ArrowUpRight size={18} /></div><h3>{project.title}</h3><p>{project.description}</p><div className="pills">{project.tools.map(tool => <Pill key={tool}>{tool}</Pill>)}</div></div></article>)}</div></section>
      <section id="skills" className="wrap section"><SectionHeading eyebrow="05 / CAPABILITIES" title="Technical Skills" /><div className="skills-grid">{Object.entries(skills).map(([name, list]) => <article className="skill-card" key={name}><h3>{name}</h3><div className="skill-list">{list.map(skill => <span key={skill}><Check size={14} />{skill}</span>)}</div></article>)}</div></section>
      <section id="leadership" className="wrap section split-section"><div><SectionHeading eyebrow="06 / COMMUNITY" title="Leadership & Activities" /></div><article className="leadership-card"><div className="lead-icon"><Users size={22} /></div><div><h3>Rotaract Club of Eskaton North</h3><p>General Member</p><span>2024–Present</span></div><ArrowUpRight size={19} /></article></section>
      <section id="achievements" className="wrap section"><SectionHeading eyebrow="07 / RECOGNITION" title="Honors & Achievements" /><div className="achievement-list">{achievements.map((item, i) => <div key={item}><span>0{i + 1}</span><h3>{item}</h3><Check size={16} /></div>)}</div></section>
      <section className="wrap section references"><SectionHeading eyebrow="08 / REFERENCES" title="Academic references." /><div className="reference-grid"><article><Quote size={20} /><h3>Dr. Muhammad Firoz Mridha</h3><p>Professor and Head (Undergraduate Program)<br />Department of Computer Science<br />American International University-Bangladesh</p><a href="mailto:firoz.mridha@aiub.edu">firoz.mridha@aiub.edu</a></article><article><Quote size={20} /><h3>Dipta Justin Gomes</h3><p>Assistant Professor<br />Department of Computer Science<br />American International University-Bangladesh</p><a href="mailto:dipta.gomes@aiub.edu">dipta.gomes@aiub.edu</a></article></div></section>
      <section id="contact" className="contact wrap"><div><p className="eyebrow">09 / CONTACT</p><h2>Let&apos;s connect.</h2><p>Open to conversations about research, software, and opportunities to learn.</p></div><div className="contact-details"><a href="mailto:yyousharashid@gmail.com"><Mail size={18} /><span><small>Email</small>yyousharashid@gmail.com</span></a><a href="tel:01749120150"><Phone size={18} /><span><small>Phone</small>01749120150</span></a><div><MapPin size={18} /><span><small>Location</small>Dhaka, Bangladesh</span></div><div className="contact-buttons"><a className="button primary" href="mailto:yyousharashid@gmail.com">Email Me <Mail size={15} /></a><a className="button secondary" href="tel:01749120150">Call Me <Phone size={15} /></a></div></div></section>
    </main><footer className="footer wrap"><div><a className="brand"><span className="brand-mark">YR</span><span>Yousha Rashid</span></a><p>Computer Science & Engineering Student | AI/ML Research Enthusiast</p></div><span>© 2026 Yousha Rashid. All rights reserved.</span></footer>
  </div>
}
